### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by anjopater** [pratikq23/side-menu-ionic-3#1]
![image](https://user-images.githubusercontent.com/19295280/52078477-71faa400-257a-11e9-9974-6bb1df1b626e.png)

![image](https://user-images.githubusercontent.com/19295280/52078262-e97c0380-2579-11e9-8b25-83d2614fb9fe.png)

Hello, thanks in advance by you contribution.

I'm traying run the project but I having the bellow error to do 'ionic serve'

any reason, looks like something with typeScript?

**Comment by pratikq23** [comment]
yes please check the version in package.Json file and try to use the same version
